### ISSUE TITLE
Не верно конвертируется дата

### ISSUE THREAD

**Issue by SeryiVolk** [Ev2geny/Sberbank2Excel#1]
Здравствуйте. 
При конвертации текстового файла дата операции типа 08.02.2020 (8 февраля 2020) в файле Excel отображается как 02.08.2020.

**Comment by Ev2geny** [comment]
Добрый день, еще раз проверил на своей выписке - у меня всё работает нормально. Может быть такое, что у вас в Excel просто отображается даты в формате mm.dd.yyyy?
Если проблема присутствует, то хотелось бы получить тестовую выписку, с помощью которой я смогу воспроизвести проблему. Чтобы избежать проблему с конфедициальностью предлагаю отредактировать текстовый файл выписки, удалив из неё конфиденциальную информацию.

**Comment by Ev2geny** [comment]
Начиная с релиза 1.3.1 в дистрибутив добавлена папка Examples. Проведите тестовую конвертацию текстовых файлов из этой папки в формат Excel, используюя sberbankPDFtext2ExcelGUI.zip. Сравните результат с файлами .xlsx, находящимися в той же папке. Если программа успешно конвертирует тестовые файлы, значит дело в формате вашего текстового файла.

Сообщите об ошибке разработчику. Желательно сделать это через инструментарий github: https://github.com/Ev2geny/Sberbank2Excel/issues. Либо сообщите об ошибке по этектронной почте (ev2geny собака gmail.com)

При информировании об ошибке необходимо приложить входной текстовый файл, с которым произошла ошибка. Т.к. такой файл в изначальном виде будет содержать персональную информацию, то рекоммендуется удалить эту информацию используя в качестве примера файл primer_dlya_soobsheniya_ob_oshibkah.txt

**Comment by Ev2geny** [comment]
проблема решена в релизе 2.0 https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v2.0
