### ISSUE TITLE
Ошибка при конвертации файла 

### ISSUE THREAD

**Issue by msnazarow** [Ev2geny/Sberbank2Excel#17]
Конвертируем файл C:/Users/msnaz/Downloads/Выписка по дебетовой карте (на русском) (1).pdf
Формат файла определён как 2107_Stavropol
Произошла ошибка при конвертации файла "file" <class 'core.exceptions.BalanceVerificationError'>
Traceback (most recent call last):
  File "core\sberbankPDF2ExcelGUI.py", line 59, in btn_convertFiles_clicked
  File "core\sberbankPDF2Excel.py", line 48, in sberbankPDF2Excel
  File "core\sberbankPDFtext2Excel.py", line 55, in sberbankPDFtext2Excel
  File "core\utils.py", line 443, in check_transactions_balance
core.exceptions.BalanceVerificationError:
            Ошибка проверки балланса по трансакциям:
                СУММА НАЧИСЛЕНИЙ - СУММА СПИСАНИЙ = 9644.349999999977
                Вычисленный баланс по всем трансакциям = 9784.120000000004

**Comment by Ev2geny** [comment]
В случае если происходит ошибка в конвертации выписки, либо есть потребность добавить новый формат, разработчику потребуется доступ к проблемной/новой выписке для исправления программы. Если из соображений конфиденциальности нет возможности переслать разработчику изначальную выписку, можно переслать анонимизированный промежуточный текстовый файл. Для этого надо сделать следующее:
https://github.com/Ev2geny/Sberbank2Excel#%D0%BA%D0%B0%D0%BA-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%8B%D0%BB%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%BD%D1%8B%D0%B9-%D1%84%D0%B0%D0%B9%D0%BB

**Comment by Ev2geny** [comment]
Проблема закрыта, т.к. не предоставлено дополнительной информации
