### ISSUE TITLE
Выписки по закрытым счетам

### ISSUE THREAD

**Issue by aruytehno** [Ev2geny/Sberbank2Excel#18]
Сбербанк не позволяет восстановить отображение карты по причине закрытия счёта. Данные хранятся 5 лет и сотрудники в офисе могут предоставить выписку и отправить файл выгрузки на почту. Ввиду отсутствия внутреннего сервиса для анализа подобных выписок, считаю актуальным продолжение работы над данным приложением с расширением возможностей анализа транзакций и автоматического построения графиков по необходимым критериям. В дальнейшем перевести сервис в онлайн-режим работы как отдельного веб-сервиса.

**Comment by Ev2geny** [comment]
**продолжение работы над данным приложением с расширением возможностей анализа транзакций**
Какое конкретно расширение возможностей вы имеете в виду?

**автоматическое построения графиков по необходимым критериям**
По моему опыту у всех своё видение графиков. Поэтому после того как данные переведены в Excel каждый может построить те графики, которые нужны конкретно ему.

**перевести сервис в онлайн-режим работы как отдельного веб-сервиса.**
Интересная идея, но я бы не стал, например, грузить свои выписки ни на какой веб сервер в силу конфиденциальности данных
