### ISSUE TITLE
При конвертации ошибка Failed verification of balance

### ISSUE THREAD

**Issue by Kreol13** [Ev2geny/Sberbank2Excel#2]
Проверялось на нескольких выгрузках за разные периоды, при попытке преобразования текстового файла через утилиту, получаем одно и то же - 
`Error occured, when converting file "file" <class 'core.exceptions.SberbankPDFtext2ExcelError'>
Traceback (most recent call last):
  File "Sberbank2Excel\core\sberbankPDFtext2ExcelGUI.py", line 61, in btn_convertFiles_clicked
  File "Sberbank2Excel\core\sberbankPDFtext2Excel.py", line 51, in sberbankPDFtext2Excel
  File "Sberbank2Excel\core\utils.py", line 182, in check_transactions_balance
core.exceptions.SberbankPDFtext2ExcelError: Failed verification of balance`

**Comment by mail-22** [comment]
похоже автор не пока не освоил тестирование ?

**Comment by Ev2geny** [comment]
Добрый день,  ошибка связана с тем, что сконвертированная выписка не прошла внутреннюю проверку:

===========================
В текстовом файле находятся величины "СУММА ПОПОЛНЕНИЙ" и "СУММА СПИСАНИЙ", после чего вычисляется их разница
Эта разница сравнивается с величиной, вычисленной путём сложения всех операций
Если разница составляет больше, чем 1 копейка, то файл Excel не генерируется (в командной строке будет сообщение об ошибке)
Таким образом достигается практически 100% гарантия, что если файл Excel был создан, то все величины записанные в него правильные
==========================
 
Но на моей  выписке всё работает.  

Для того чтобы разбираться дальше необходимо получить тестовую выписку, с помощью которой я смогу воспроизвести проблему. Чтобы избежать проблему с конфедициальностью предлагаю отредактировать текстовый файл выписки, удалив из неё конфиденциальную информацию.

**Comment by Ev2geny** [comment]
Начиная с релиза 1.3.1 в дистрибутив добавлена папка Examples. Проведите тестовую конвертацию текстовых файлов из этой папки в формат Excel, использую sberbankPDFtext2ExcelGUI. Сравните результат с файлами .xlsx, находящимися в той же папке. Если программа успешно конвертирует тестовые файлы, значит дело в формате вашего текстового файла.

Сообщите об ошибке разработчику. Желательно сделать это через инструментарий github: https://github.com/Ev2geny/Sberbank2Excel/issues. Либо сообщите об ошибке по электронной почте (ev2geny собака gmail.com)

При информировании об ошибке необходимо приложить входной текстовый файл, с которым произошла ошибка. Т.к. такой файл в изначальном виде будет содержать персональную информацию, то рекомендуется удалить эту информацию используя в качестве примера файл primer_dlya_soobsheniya_ob_oshibkah.txt

**Comment by Ev2geny** [comment]
проблема решена в релизе 2.0 https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v2.0
