### ISSUE TITLE
Добавить вывод в CSV

### ISSUE THREAD

**Issue by mikhailnov** [Ev2geny/Sberbank2Excel#20]
Здравствуйте!
Делаю программу с веб и cli интерфейсом [FreeKazna](https://github.com/freekazna/freekazna), которая умеет брать выгрузки из разных банков и заносить расходы из них в свою единую базу. Планирую сделать интерфейс для учета расходов, на какой вид платежей сколько денег ушло и т.д. Планирую сделать готовые RPM-пакеты и контейнерные образы для быстрого запуска у себя.
В вашей утилите есть CLI-интерфейс, под Линуксом по идее должна без проблем работать, даже GUI (tkinter есть на linux), я бы мог из freekazna вызывать Sberbank2Excel для конвертирования предоставленного пользователем PDF в CSV и далее читать полученный CSV. xlsx можно через libreoffice конвертировать в csv, но это будет весьма монстроузорно.
Хотелось бы, чтоб был формат вывода csv. Разделитель полей любой, обычно удобнее всего точка с запятой.

**Comment by mikhailnov** [comment]
да, так и хотел: пользователь загружает в веб-морду freekazna pdf от сбербанка, а она скармливается этому скрипту. Спасибо!

**Comment by cypok** [comment]
@mikhailnov, если не жалко процессорного времени на конвертации туда-сюда, то можно установить набор утилит [csvkit](https://github.com/wireservice/csvkit) и в его составе есть утилита для конвертации xlsx в csv: `in2csv foo.xlsx > foo.csv`.

**Comment by Ev2geny** [comment]
Функционал добавлен в релиз [4.1.0](https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v4.1.0)
