### ISSUE TITLE
Добавить конвертацию выписок по счету

### ISSUE THREAD

**Issue by artforlife** [Ev2geny/Sberbank2Excel#22]
Было бы здорово, если бы вы сделали возможность конвертировать выписки не только с карт, но и сo счетов. Я поигрался с кодом и у меня это заработало. Однако приводить в порядок времени нет. Там в принципе похожи шаблоны. Нужно лишь поменять валидацию заголовка шапки, а также метод просчета колонки данных `value_account_currency` для Панды. В выписке по карте транзакция без знака это списание, а в выписке по счету транзакция без знака это наоборот поступление. 

Если заинтересует, могу сделать PR того, что у меня есть.

**Comment by Ev2geny** [comment]
Да, конечно, делайте PR, посмотрим что у вас есть.

**Comment by Ev2geny** [comment]
Функционал добавлен в релиз [4.1.0](https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v4.1.0)

**Comment by artforlife** [comment]
У меня не работает.

```(sberbank-conversion) ➜  Sberbank2Excel-New git:(master) ✗ python core/sberbankPDF2Excel.py Statement\ \(25\).pdf
Namespace(input_file_name='Statement (25).pdf', output_Excel_file_name=None, perform_balance_check=True, format='auto', output_file_type='xlsx', leave_intermediate_txt_file=False)
format='auto'
******************************
Конвертируем файл Statement (25).pdf
Traceback (most recent call last):
  File "/homeuser/SourceCode/Sberbank2Excel-New/core/sberbankPDF2Excel.py", line 90, in <module>
    main()
  File "/home/user/SourceCode/Sberbank2Excel-New/core/sberbankPDF2Excel.py", line 82, in main
    sberbankPDF2Excel(input_file_name = args.input_file_name,
  File "/home/user/SourceCode/Sberbank2Excel-New/core/sberbankPDF2Excel.py", line 55, in sberbankPDF2Excel
    result = sberbankPDFtext2Excel(tmp_txt_file_name,
  File "/home/user/SourceCode/Sberbank2Excel-New/core/sberbankPDFtext2Excel.py", line 64, in sberbankPDFtext2Excel
    extractor_type = determine_extractor_auto(file_text)
  File "/home/user/SourceCode/Sberbank2Excel-New/core/extractors_generic.py", line 26, in determine_extractor_auto
    raise exceptions.InputFileStructureError("Неизвecтный формат выписки, ни один из экстракторов не подходят")
exceptions.InputFileStructureError: Неизвecтный формат выписки, ни один из экстракторов не подходят
```

**Comment by Ev2geny** [comment]
> У меня не работает.
> 
> ```
> Namespace(input_file_name='Statement (25).pdf', output_Excel_file_name=None, perform_balance_check=True, format='auto', output_file_type='xlsx', leave_intermediate_txt_file=False)
> format='auto'
> ******************************
> Конвертируем файл Statement (25).pdf
> Traceback (most recent call last):
>   File "/homeuser/SourceCode/Sberbank2Excel-New/core/sberbankPDF2Excel.py", line 90, in <module>
>     main()
>   File "/home/user/SourceCode/Sberbank2Excel-New/core/sberbankPDF2Excel.py", line 82, in main
>     sberbankPDF2Excel(input_file_name = args.input_file_name,
>   File "/home/user/SourceCode/Sberbank2Excel-New/core/sberbankPDF2Excel.py", line 55, in sberbankPDF2Excel
>     result = sberbankPDFtext2Excel(tmp_txt_file_name,
>   File "/home/user/SourceCode/Sberbank2Excel-New/core/sberbankPDFtext2Excel.py", line 64, in sberbankPDFtext2Excel
>     extractor_type = determine_extractor_auto(file_text)
>   File "/home/user/SourceCode/Sberbank2Excel-New/core/extractors_generic.py", line 26, in determine_extractor_auto
>     raise exceptions.InputFileStructureError("Неизвecтный формат выписки, ни один из экстракторов не подходят")
> exceptions.InputFileStructureError: Неизвecтный формат выписки, ни один из экстракторов не подходят
> ```

Спасибо за тестирование, но тут похоже без примера неработающей выписки не обойдёшься, т.к. на моих выписках и на выписках еще одного пользователя всё работает. 

Речь точно идёт про вариант выписки, которую я назвал [SBER_PAYMENT_2208](https://github.com/Ev2geny/Sberbank2Excel/blob/master/misc/format_examples/SBER_PAYMENT_2208.png) ?

В любом случае как тут поступать написано в [ЧаВо](https://github.com/Ev2geny/Sberbank2Excel#id11).

Если не можете предоставить выписку либо анонимизированный её вариант, то попробуйте сами найти проблему запустив самотестирование модуля [extractor_SBER_PAYMENT_2208.py](https://github.com/Ev2geny/Sberbank2Excel/blob/master/core/extractor_SBER_PAYMENT_2208.py)

`py extractor_SBER_PAYMENT_2208.py промежуточный_текстовый_файл.txt`
