### ISSUE TITLE
У Сбера появился новый формат выписки по счету

### ISSUE THREAD

**Issue by artforlife** [Ev2geny/Sberbank2Excel#24]
Утилита его не распознает (ошибочно распознает как SBER_PAYMENT_2208) и выдает ошибку

![Untitled](https://user-images.githubusercontent.com/8064423/210008399-cf34ef23-93a0-43aa-b9ad-be7e4ad925d5.png)

**Comment by Ev2geny** [comment]
Здравствуйте,

спасибо за сообщение об ошибке.

Да, действительно у меня тоже платёжный счёт перестал работать на новых выписках.

Исправлю как время найду (недели 2 наверное).

**Comment by Ev2geny** [comment]
Ну ясно, что они изменили формат.
Исчезла колонка **Остаток по счёту в валюте счёта**

![image](https://user-images.githubusercontent.com/59611075/210095269-95e3ad70-0da2-4ea7-83e6-199c32fef76b.png)

Доработаем

**Comment by DalasDV** [comment]
Аналогичная история с выпиской по дебетовой карте (SBER_DEBIT_2107). Причина та же.

**Comment by Ev2geny** [comment]
Функционал добавлен в релизе[ 4.2.0](https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v4.2.0)
