### ISSUE TITLE
отличная прога! только НЕ работает!

### ISSUE THREAD

**Issue by mail-22** [Ev2geny/Sberbank2Excel#3]
отличная прога! только НЕ работает!

https://prnt.sc/sr6bxy

скриншот ошибки
(ошибка на всех отчетах)

**Comment by Kreol13** [comment]
Эту ошибку я получил, сделав конвертацию через Adobe Reader, дальше, как автор и пишет попробовал через Foxit. И получил уже ту, которая у меня указана в issue#2

**Comment by Ev2geny** [comment]
Начиная с релиза 1.3.1 в дистрибутив добавлена папка Examples. Проведите тестовую конвертацию текстовых файлов из этой папки в формат Excel, использую sberbankPDFtext2ExcelGUI. Сравните результат с файлами .xlsx, находящимися в той же папке. Если программа успешно конвертирует тестовые файлы, значит дело в формате вашего текстового файла.

Сообщите об ошибке разработчику. Желательно сделать это через инструментарий github: https://github.com/Ev2geny/Sberbank2Excel/issues. Либо сообщите об ошибке по электронной почте (ev2geny собака gmail.com)

При информировании об ошибке необходимо приложить входной текстовый файл, с которым произошла ошибка. Т.к. такой файл в изначальном виде будет содержать персональную информацию, то рекомендуется удалить эту информацию используя в качестве примера файл primer_dlya_soobsheniya_ob_oshibkah.txt

**Comment by Ev2geny** [comment]
проблема решена в релизе 2.0 https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v2.0
