### ISSUE TITLE
Ошибка парсинга расходов в валюте

### ISSUE THREAD

**Issue by Zorba131** [Ev2geny/Sberbank2Excel#31]
Строка из промежуточного файла txt
`05.08.2022	09:26	WWW.TAXI.YANDEX.RU       YEREVAN      ARM	-12,57`
`06.08.2022	428911	Отдых и развлечения	-80,00 AMD`

Скрин из лога
![image](https://github.com/Ev2geny/Sberbank2Excel/assets/78138975/b043d6bc-46f2-4cb9-9aeb-a4ad051056be)

Скрин из pdf
![image](https://github.com/Ev2geny/Sberbank2Excel/assets/78138975/cf91c70e-f6d9-4202-8c42-6b2e782c0c26)

**Comment by Ev2geny** [comment]
Добрый день, спасибо, что сообщили.

Но очень хотелось бы получить выписку целиком, иначе процесс отладки займёт непозволительно долго

Можно сделать выписку только из 1 дня и переслать её мне как написано в [Приложение Б. Как безопасно пересылать проблемный файл](https://github.com/Ev2geny/Sberbank2Excel#id22)

**Comment by Zorba131** [comment]
[test.txt](https://github.com/Ev2geny/Sberbank2Excel/files/12814032/test.txt)

**Comment by Ev2geny** [comment]
Добрый день, попробуйте вот эту версию ([sberbankPDF2ExcelGUI_v4.5.1b](https://drive.google.com/file/d/1i4H2X5Btu__-KM1ub5v_WPlsRNvc9PtJ/view?usp=sharing)), должно работать.

**Comment by Ev2geny** [comment]
Не получил подтверждения от @Zorba131, что решение работает, но в любом случае изменения вошли в релиз [4.5.1](https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v.4.5.1)
