### ISSUE TITLE
Игнорируется приходная операция c кодом авторизации 0

### ISSUE THREAD

**Issue by shcherbakov-vadim** [Ev2geny/Sberbank2Excel#33]
Версия 4.5.0
При поступлении кэшбэка по программе privetmir.ru, данная сумма не попадает в итоговый файл. При этом в промежуточном текстовом файле она есть.
Конвертируем файл ./test.pdf
Формат файла определён как SBER_DEBIT_2212

            Ошибка проверки балланса по трансакциям:
                Вычисленный баланс по информации в шапке выписки = -50.0
                Вычисленный баланс по всем трансакциям = -250.0

Создан файл ./test.xlsx

[test.txt](https://github.com/Ev2geny/Sberbank2Excel/files/13666029/test.txt)
[test.xlsx](https://github.com/Ev2geny/Sberbank2Excel/files/13666030/test.xlsx)

**Comment by Ev2geny** [comment]
Проблему воспроизвёл, посмотрю.
Проблема возникла из-за того, что код авторизации какой-то странный (состоит только из 0)
`27.11.2023	0	Прочие операции. Операция по карте ****2872`

P.S. благодарю за качественное сообщение о проблеме.

**Comment by Ev2geny** [comment]
Исправлено в релизе [4.5.2](https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v.4.5.2)

**Comment by shcherbakov-vadim** [comment]
~/util/Sberbank2Excel/core$ python3 ./sberbankPDF2Excel.py  -h
Traceback (most recent call last):
  File "/home/vadim/util/Sberbank2Excel/core/./sberbankPDF2Excel.py", line 9, in <module>
    from sberbankPDFtext2Excel import sberbankPDFtext2Excel, genarate_PDFtext2Excel_argparser
  File "/home/vadim/util/Sberbank2Excel/core/sberbankPDFtext2Excel.py", line 43, in <module>
    output_file_name:str|None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Ev2geny** [comment]
Я правильно понимаю, что вы запускаете в Linux из командной строки?
У вас какая версия python?

**Comment by shcherbakov-vadim** [comment]
Да, из командной строки. Версия Python 3.9.5

**Comment by Ev2geny** [comment]
Нужен python 3.11
Конкретно в ошибке, которую Вы указали он не понимает вот этот грамматику, которая в 3.10 введена
https://peps.python.org/pep-0604/

**Comment by shcherbakov-vadim** [comment]
Понятно, буду обращать внимание на первую строку в requirements.txt. 
Проблема с конвертацией pdf разрешилась
