### ISSUE TITLE
Добавить поддержку счетов "Пенсионный плюс" и "Активный возраст"

### ISSUE THREAD

**Issue by Ev2geny** [Ev2geny/Sberbank2Excel#35]
По [заявке ](https://github.com/Ev2geny/Sberbank2Excel/issues/34#issuecomment-1972515235) от @lensovet

**Comment by lensovet** [comment]
Отправил файл на почту. Клянусь что ПП работал год назад.

**Comment by Ev2geny** [comment]
Добрый день

спасибо за образец.

вот, проверьте, должно работать
https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v.4.6.0

**Comment by lensovet** [comment]
спасибо, интересный момент

- если открывать в Excel, никаких проблем
- в программе Numbers, пользовательский формат слетает, и даты отображаются так: `YYYY-05-DD`. Не конец света, просто поменял формат на стандартную дату и все ок, но хотел дать знать поскольку с выпиской от карты Мир таких проблем нет.

Также могу подтвердить что счет Пенсионный плюс имеет такой же формат и успешно проходит если его поменять на Активный возраст. Разница в двух местах:

- `Выписка из лицевого счёта по вкладу «Пенсионный-плюс»1` в шапке
- Тип вклада `Пенсионный-плюс ` в шапке

**Comment by Ev2geny** [comment]
> Также могу подтвердить что счет Пенсионный плюс имеет такой же формат и успешно проходит если его поменять на Активный возраст. Разница в двух местах:

Спасибо за подтверждение. 
Проверьте пожалуйста еще раз, действительно ли нужно ли что-то менять. Я внес изменения в последний релиз, с расчётом на то, что все счета, похожие на [SBER_SAVING_2303](https://github.com/Ev2geny/Sberbank2Excel/blob/v.4.6.0/misc/format_examples/SBER_SAVING_2303.png) должны успешно конвертироваться. Программа проверяет наличие последовательности  `Выписка из лицевого счёта по вкладу « ......»`

**Comment by lensovet** [comment]
Добрый день, изменения нужны, потому что я тестировал оба файла с тегом 4.6.0. Активный возраст работал, пенсионный плюс нет. Может быть потом что в названии дефис? Как только изменил название счета и тип вклада, все работало.

**Comment by lensovet** [comment]
Посмотрел код, именно так. `\W\s` не будет включать в себя `-`, который присутствует в названии ПП.

**Comment by lensovet** [comment]
мне кажется что лучше бы там иметь поиск типа `Выписка из лицевого счёта по вкладу «[^»]+»`

**Comment by lensovet** [comment]
```
diff --git a/core/extractor_SBER_SAVING_2303.py b/core/extractor_SBER_SAVING_2303.py
index f977ae0..4e828ec 100644
--- a/core/extractor_SBER_SAVING_2303.py
+++ b/core/extractor_SBER_SAVING_2303.py
@@ -36,7 +36,7 @@ class SBER_SAVING_2303(Extractor):
         If these signatures are not found, then exceptions.InputFileStructureError() is raised
         """
 
-        test1 = re.search(r'Выписка из лицевого счёта по вкладу «[\w\s]*»', self.bank_text, re.IGNORECASE)
+        test1 = re.search(r'Выписка из лицевого счёта по вкладу «[^»]+»', self.bank_text, re.IGNORECASE)
         # print(f"{test1=}")
```

Проверил, работает.

**Comment by Ev2geny** [comment]
Отлично! спасибо!

вот так наверное тоже будет работать. Чтобы он только в одной строке искал бы.

```py
test1 = re.search(r'Выписка из лицевого счёта по вкладу «[^\n]*»', self.bank_text, re.IGNORECASE)
```

**Comment by lensovet** [comment]
Да норм, работает. Правда я предпочитаю именно `+` вместо `*` на всякий пожарный типа, но это не принципиально)

**Comment by lensovet** [comment]
Я вот только не в курсе насчет того как Питон обрабатывает `\n` и `\r` на винде. На всех никсах включая мак `\n` без проблем.

**Comment by lensovet** [comment]
Да, не горит

**Comment by Ev2geny** [comment]
Исправлено в релизе [4.6.1](https://github.com/Ev2geny/Sberbank2Excel/releases/tag/v4.6.1)
