### ISSUE TITLE
не работает выписка

### ISSUE THREAD

**Issue by Cid0r0v1ch** [Ev2geny/Sberbank2Excel#38]
сделал выписку из сбера выходит такая ошибка
![image](https://github.com/Ev2geny/Sberbank2Excel/assets/87601891/8fb56a73-9c17-4202-a9f2-94ca34d52177)

**Comment by Ev2geny** [comment]
Здравствуйте, а какую выписку вы пытаетесь сконвертировать?
На что она похожа?
https://github.com/Ev2geny/Sberbank2Excel/tree/master/misc/format_examples

**Comment by Ev2geny** [comment]
проблема закрыта и-за отсутствии обратной связи.
