### ISSUE TITLE
Проблема с вычислением баланса

### ISSUE THREAD

**Issue by glebasos** [Ev2geny/Sberbank2Excel#41]
VISA CLASSIC SBER_DEBIT_2212
При расчётё получаю ошибку
`<class 'exceptions.BalanceVerificationError'>
Traceback (most recent call last):
  File "sberbankPDF2ExcelGUI.py", line 61, in btn_convertFiles_clicked
  File "sberbankPDF2Excel.py", line 66, in sberbankPDF2Excel
  File "sberbankPDFtext2Excel.py", line 119, in sberbankPDFtext2Excel
  File "utils.py", line 67, in check_transactions_balance
exceptions.BalanceVerificationError:
            Ошибка проверки балланса по трансакциям:
                Вычисленный баланс по информации в шапке выписки = 156580.93999999994
                Вычисленный баланс по всем трансакциям = 151480.94`

Файл в тхт прилагаю, на нём такая же ошибка
[vypiska.txt](https://github.com/user-attachments/files/16010435/vypiska.txt)

**Comment by Ev2geny** [comment]
Ок, спасибо. посмотрю.

**Comment by Ev2geny** [comment]
Если воспользоваться опцией **Игнорировать результаты сверки баланса по транзакциям и в шапке выписки** то создаётся Excel c 392 трансакциями. Приглашаю вас тоже поискать действительно ли какая-то трансакция пропущена. Ваша помощь тут сильно ускорит весь процесс, т.к. тут есть два варианта.

- Либо **Sberbank2Excel** действительно пропускает какую-то трансакцию

- Либо сбер сам неправильно считает свой баланс. Такая проблема [тоже сообщалась](https://github.com/Ev2geny/Sberbank2Excel/issues/13). Причём именно для кредиток.

Либо можно еще создать 12 выписок (1 на каждый месяц) и посмотреть присутствует ли проблема в каждой из них. Это поможет сузить поиск.

**Comment by Ev2geny** [comment]
Т.к дополнительной информации от @glebasos не поступило, то будет считать проблему закрытой.
