### ISSUE TITLE
КУДА ДОНАТИТЬ ?

### ISSUE THREAD

**Issue by nkorsakov** [Ev2geny/Sberbank2Excel#6]
ТЫ сэкономил неделю работы мне !!!
КУДА ДОНАТИТЬ ?

**Comment by Ev2geny** [comment]
@nkorsakov благодарю за положительную обратную связь!

**Comment by RudenkoRNK** [comment]
Горячо плюсую!

**Comment by Ev2geny** [comment]
Для донатов можно использовать:
https://qiwi.com/n/SBERBANK2EXCEL

Также добавил в описание https://github.com/Ev2geny/Sberbank2Excel

**Comment by Ev2geny** [comment]
Пусть висит
