### ISSUE TITLE
Не конвертируются файлы выписки формата 2107_Stavropol

### ISSUE THREAD

**Issue by Hapuga** [Ev2geny/Sberbank2Excel#8]
На всех файлах (пробовал с разных карт и за разные периоды) выдается ошибка проверки баланса:

log4cplus:ERROR No appenders could be found for logger (DSL).
log4cplus:ERROR Please initialize the log4cplus system properly.
Конвертируем файл D:/sbrf stavro.pdf
Формат файла определён как 2107_Stavropol
Произошла ошибка при конвертации файла "file" <class 'core.exceptions.BalanceVerificationError'>
Traceback (most recent call last):
  File "core\sberbankPDF2ExcelGUI.py", line 56, in btn_convertFiles_clicked
  File "core\sberbankPDF2Excel.py", line 22, in sberbankPDF2Excel
  File "core\sberbankPDFtext2Excel.py", line 57, in sberbankPDFtext2Excel
  File "core\utils.py", line 389, in check_transactions_balance
core.exceptions.BalanceVerificationError:
            Ошибка проверки балланса по трансакциям:
                СУММА НАЧИСЛЕНИЙ - СУММА СПИСАНИЙ = -42604.820000000065
                Вычисленный баланс по всем трансакциям = -93900.78000000003

Пропускаем конвертацию этого файла
!!!!!!! 1 файл(а) из 1 не были сконвертированы

**Comment by Ev2geny** [comment]
Да, подтверждаю проблему. Ставропольский формат выписки теперь доехал и до Москвы и я теперь могу делать свои собственные выписки и вижу, что не на всех выписках работает.
Исправлю проблему на днях.
